import type { Config } from 'tailwindcss';

// Design tokens ported 1:1 from FrontEnd/apex_elite_aesthetic/DESIGN.md and the
// per-screen Stitch exports (see FrontEnd/*/code.html <script id="tailwind-config">).
// Keeping these identical across every screen is what makes the Stitch -> Next.js
// port pixel-accurate instead of "inspired by".
const config: Config = {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container': '#201f1f',
        'tertiary-fixed-dim': '#c8c6c5',
        'surface-bright': '#3a3939',
        surface: '#131313',
        'on-primary-container': '#541200',
        'on-tertiary-fixed-variant': '#474746',
        'on-tertiary-container': '#2a2a2a',
        background: '#131313',
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#e9c349',
        'on-secondary-fixed': '#241a00',
        'surface-container-lowest': '#0e0e0e',
        tertiary: '#c8c6c5',
        'on-secondary-fixed-variant': '#574500',
        'surface-container-low': '#1c1b1b',
        'on-tertiary': '#313030',
        'on-surface-variant': '#e4beb4',
        'on-background': '#e5e2e1',
        'outline-variant': '#5b4039',
        'inverse-surface': '#e5e2e1',
        'surface-container-high': '#2a2a2a',
        error: '#ffb4ab',
        'surface-tint': '#ffb5a0',
        'on-surface': '#e5e2e1',
        'inverse-primary': '#b02f00',
        'primary-fixed-dim': '#ffb5a0',
        outline: '#ab8980',
        'tertiary-fixed': '#e5e2e1',
        'surface-container-highest': '#353534',
        'secondary-container': '#af8d11',
        'error-container': '#93000a',
        'on-primary': '#5f1500',
        'on-primary-fixed': '#3b0900',
        'primary-container': '#c84b24',
        'on-tertiary-fixed': '#1c1b1b',
        primary: '#ffb5a0',
        'primary-fixed': '#ffdbd1',
        'surface-variant': '#353534',
        secondary: '#e9c349',
        'on-primary-fixed-variant': '#862200',
        'tertiary-container': '#929090',
        'on-secondary': '#3c2f00',
        'inverse-on-surface': '#313030',
        'on-secondary-container': '#342800',
        'surface-dim': '#131313',
        'secondary-fixed': '#ffe088',
        'on-error': '#690005',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'container-margin-desktop': '64px',
        base: '8px',
        'container-margin-mobile': '20px',
        'section-gap': '80px',
      },
      fontFamily: {
        'label-caps': ['Inter', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Montserrat', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

export default config;
