import { LobbyType, type MatchCardData, type PlayerAvatar } from '@/types/lobby';

const AVATARS = [
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=96&h=96&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=96&h=96&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=96&h=96&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=96&h=96&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=96&h=96&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=96&h=96&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=96&h=96&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=96&h=96&fit=crop&crop=faces',
];

const PADEL_COVER =
  'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=900&h=700&fit=crop';

function players(count: number, start = 0): PlayerAvatar[] {
  return Array.from({ length: count }, (_, i) => {
    const idx = (start + i) % AVATARS.length;
    return {
      id: `p-${start + i}`,
      name: `Hráč ${start + i + 1}`,
      image: AVATARS[idx] ?? null,
    };
  });
}

export const MOCK_MATCH_CARDS: MatchCardData[] = [
  {
    id: 'match-padel-kings-challenge',
    type: LobbyType.TEAM_VS_TEAM,
    title: 'Bratislava Smashers',
    sport: 'Padel',
    dateLabel: 'Zajtra',
    timeLabel: '18:30',
    venueName: 'Aurial Padel Bratislava',
    city: 'Bratislava',
    distanceKm: 2.0,
    playersFilled: 2,
    playersTotal: 4,
    skillLevel: 'ADVANCED',
    pricePerPersonEur: 7,
    roster: players(2, 2),
    teamA: players(2, 2),
    teamBOpenSlots: 2,
    teamName: 'Bratislava Smashers',
    teamRecord: '5V - 1P',
    teamLogoUrl: AVATARS[0] ?? null,
    challengeTerms: 'Kurt rezervovaný • Náklady napoly',
    ctaLabel: 'Prijať výzvu (Challenge)',
    sportIcon: 'padel',
    iconAccent: 'orange',
  },
  {
    id: 'match-player-martin',
    type: LobbyType.SINGLE_PLAYER_1,
    title: 'Hľadám parťáka',
    sport: 'Padel',
    dateLabel: 'Dnes',
    timeLabel: '17:30',
    venueName: 'Park 21',
    city: 'Bratislava',
    distanceKm: 0.9,
    playersFilled: 1,
    playersTotal: 2,
    skillLevel: 'INTERMEDIATE',
    pricePerPersonEur: 8,
    roster: [
      {
        id: 'martin-k',
        name: 'Martin K.',
        image: AVATARS[0] ?? null,
      },
    ],
    ctaLabel: 'Pripojiť sa (1-Klik)',
    sportIcon: 'padel',
    iconAccent: 'orange',
    paymentDisclaimer: 'Rezervácia kurtu a platba priamo na športovisku.',
  },
  {
    id: 'match-padel-plus1',
    type: LobbyType.SINGLE_PLAYER_1,
    title: 'Hľadám parťáka (+1)',
    sport: 'Padel',
    dateLabel: 'Dnes',
    timeLabel: '19:00',
    venueName: 'Padelkings',
    city: 'Bratislava',
    distanceKm: 1.2,
    playersFilled: 3,
    playersTotal: 4,
    skillLevel: 'INTERMEDIATE',
    pricePerPersonEur: 8,
    roster: players(3, 0),
    ctaLabel: 'Pripojiť sa (1-Klik)',
    sportIcon: 'padel',
    iconAccent: 'orange',
    coverUrl: PADEL_COVER,
    paymentDisclaimer: 'Rezervácia kurtu a platba priamo na športovisku.',
  },
  {
    id: 'match-padel-park21-squad',
    type: LobbyType.RECURRING_SQUAD,
    title: 'Utorkový Padel Park 21',
    sport: 'Padel',
    dateLabel: 'Utorok',
    timeLabel: '18:00',
    venueName: 'Park 21',
    city: 'Bratislava',
    distanceKm: 0.8,
    playersFilled: 11,
    playersTotal: 12,
    skillLevel: 'MEDIUM',
    pricePerPersonEur: null,
    roster: players(6, 4),
    ctaLabel: 'Požiadať o vstup do Squadu',
    sportIcon: 'padel',
    iconAccent: 'lime',
    recurringNote: 'Každý utorok 18:00',
    squadStatus: 'Niekto vypadol, uvoľnené miesto na najbližší termín',
    substituteLabel: 'Voľný náhradník (Zobrať miesto)',
  },
  {
    id: 'match-football-tehelne',
    type: LobbyType.SINGLE_PLAYER_1,
    title: 'Hľadám hráča (+1)',
    sport: 'Futbal',
    dateLabel: 'Dnes',
    timeLabel: '20:00',
    venueName: 'Tehelné pole',
    city: 'Bratislava',
    distanceKm: 1.5,
    playersFilled: 4,
    playersTotal: 5,
    skillLevel: 'INTERMEDIATE',
    pricePerPersonEur: 7,
    roster: players(4, 1),
    ctaLabel: 'Pripojiť sa (1-Klik)',
    sportIcon: 'football',
    iconAccent: 'orange',
    paymentDisclaimer: 'Rezervácia kurtu a platba priamo na športovisku.',
  },
  {
    id: 'match-tennis-fitcamp',
    type: LobbyType.TEAM_VS_TEAM,
    title: 'NTC Challengers',
    sport: 'Tenis',
    sportFormat: 'Dvojhra',
    dateLabel: 'Piatok',
    timeLabel: '18:00',
    venueName: 'FitCamp',
    city: 'Bratislava',
    distanceKm: 2.5,
    playersFilled: 2,
    playersTotal: 4,
    skillLevel: 'ADVANCED',
    pricePerPersonEur: 7,
    roster: players(2, 3),
    teamA: players(2, 3),
    teamBOpenSlots: 2,
    teamName: 'NTC Challengers',
    teamRecord: '3V - 2P',
    challengeTerms: 'Kurt rezervovaný • Náklady napoly',
    ctaLabel: 'Prijať výzvu (Challenge)',
    sportIcon: 'tennis',
    iconAccent: 'lime',
  },
  {
    id: 'match-tennis-ntc-squad',
    type: LobbyType.RECURRING_SQUAD,
    title: 'Pondelkový Tenis NTC',
    sport: 'Tenis',
    dateLabel: 'Pondelok',
    timeLabel: '18:00',
    venueName: 'NTC Bratislava',
    city: 'Bratislava',
    distanceKm: 1.5,
    playersFilled: 7,
    playersTotal: 8,
    skillLevel: 'INTERMEDIATE',
    pricePerPersonEur: 8,
    roster: players(6, 0),
    ctaLabel: 'Požiadať o vstup do Squadu',
    sportIcon: 'tennis',
    iconAccent: 'orange',
    recurringNote: 'Každý pondelok 18:00',
    squadStatus: 'Niekto vypadol, uvoľnené miesto na najbližší termín',
  },
  {
    id: 'match-basketball-downtown',
    type: LobbyType.SINGLE_PLAYER_1,
    title: 'Streetball +1',
    sport: 'Basketbal',
    dateLabel: 'Dnes',
    timeLabel: '19:30',
    venueName: 'Pasienky',
    city: 'Bratislava',
    distanceKm: 2.1,
    playersFilled: 4,
    playersTotal: 5,
    skillLevel: 'INTERMEDIATE',
    pricePerPersonEur: null,
    roster: players(4, 5),
    ctaLabel: 'Pripojiť sa (1-Klik)',
    sportIcon: 'basketball',
    iconAccent: 'orange',
  },
  {
    id: 'match-basketball-3v3',
    type: LobbyType.TEAM_VS_TEAM,
    title: 'Downtown Hoops',
    sport: 'Basketbal',
    dateLabel: 'Zajtra',
    timeLabel: '18:00',
    venueName: 'Eurovea Court',
    city: 'Bratislava',
    distanceKm: 1.8,
    playersFilled: 3,
    playersTotal: 6,
    skillLevel: 'ADVANCED',
    pricePerPersonEur: 5,
    roster: players(3, 2),
    teamA: players(3, 2),
    teamBOpenSlots: 3,
    teamName: 'Downtown Hoops',
    teamRecord: '4V - 2P',
    challengeTerms: 'Half-court • Winner stays',
    ctaLabel: 'Prijať výzvu (Challenge)',
    sportIcon: 'basketball',
    iconAccent: 'orange',
  },
  {
    id: 'match-squash-plus1',
    type: LobbyType.SINGLE_PLAYER_1,
    title: 'Squash evening +1',
    sport: 'Squash',
    dateLabel: 'Dnes',
    timeLabel: '20:00',
    venueName: 'Squashland',
    city: 'Bratislava',
    distanceKm: 1.4,
    playersFilled: 1,
    playersTotal: 2,
    skillLevel: 'INTERMEDIATE',
    pricePerPersonEur: 9,
    roster: [
      { id: 'squash-host', name: 'Peter M.', image: AVATARS[2] ?? null },
    ],
    ctaLabel: 'Pripojiť sa (1-Klik)',
    sportIcon: 'tennis',
    iconAccent: 'orange',
  },
  {
    id: 'match-running-crew',
    type: LobbyType.RECURRING_SQUAD,
    title: 'Morning Run Dunaj',
    sport: 'Running',
    dateLabel: 'Streda',
    timeLabel: '07:00',
    venueName: 'Apollo Bridge',
    city: 'Bratislava',
    distanceKm: 0.6,
    playersFilled: 8,
    playersTotal: 12,
    skillLevel: 'MEDIUM',
    pricePerPersonEur: null,
    roster: players(5, 1),
    ctaLabel: 'Požiadať o vstup do Squadu',
    sportIcon: 'football',
    iconAccent: 'lime',
    recurringNote: 'Každú stredu 07:00',
    squadStatus: 'Open tempo run · 8–10 km',
  },
  {
    id: 'match-volleyball-beach',
    type: LobbyType.TEAM_VS_TEAM,
    title: 'Beach Volley Crew',
    sport: 'Volleyball',
    dateLabel: 'Sobota',
    timeLabel: '16:00',
    venueName: 'Tyršovo nábrežie',
    city: 'Bratislava',
    distanceKm: 2.3,
    playersFilled: 4,
    playersTotal: 8,
    skillLevel: 'INTERMEDIATE',
    pricePerPersonEur: null,
    roster: players(4, 3),
    teamA: players(4, 3),
    teamBOpenSlots: 4,
    teamName: 'Beach Volley Crew',
    teamRecord: '2V - 1P',
    challengeTerms: 'Sand court • Friendly',
    ctaLabel: 'Prijať výzvu (Challenge)',
    sportIcon: 'basketball',
    iconAccent: 'orange',
  },
  {
    id: 'match-hockey-pickup',
    type: LobbyType.SINGLE_PLAYER_1,
    title: 'Pickup hokej +2',
    sport: 'Hockey',
    dateLabel: 'Piatok',
    timeLabel: '21:00',
    venueName: 'Ondrej Nepela Arena',
    city: 'Bratislava',
    distanceKm: 3.0,
    playersFilled: 8,
    playersTotal: 10,
    skillLevel: 'ADVANCED',
    pricePerPersonEur: 12,
    roster: players(6, 0),
    ctaLabel: 'Pripojiť sa (1-Klik)',
    sportIcon: 'football',
    iconAccent: 'purple',
  },
];

export function filterMatchCards(
  items: MatchCardData[],
  tab: 'ALL' | LobbyType,
): MatchCardData[] {
  if (tab === 'ALL') return items;
  return items.filter((item) => item.type === tab);
}
